default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kelly_development

test:
  <<: *default
  database: kelly_test

production:
  url: <%= ENV['DATABASE_URL'] %>
